import { build } from './build'
import type { SiteConfig } from '../types'

export function createAvtoSite(): SiteConfig {
  return build('avto', {
    accent: '#ff5a1f',
    text: {
      'brand.name': 'Mator Servis',
      'home.hero.title': 'Dəqiq diaqnostika, səliqəli təmir',
      'home.hero.lead':
        'Mühərrik, əyləc, asqı və elektrik sistemləri üzrə servis. Nəyin dəyişdiyini göstərir, işə başlamazdan əvvəl qiyməti deyirik.',
      'home.hero.cta': 'Servisə yazıl',
      'home.hero.chip': 'Avtoservis',
      'home.services.title': 'İş növləri',
      'home.services.link': 'Bütün işlər',
      'home.process.title': 'Servisə gələndə',
      'home.process.1.title': 'Qəbul',
      'home.process.1.text': 'Problemi dinləyir, maşını baxışdan keçiririk.',
      'home.process.2.title': 'Diaqnostika',
      'home.process.2.text': 'Səbəbi tapır, görüləcək işlərin siyahısını hazırlayırıq.',
      'home.process.3.title': 'Razılaşma',
      'home.process.3.text': 'Qiyməti və müddəti işə başlamazdan əvvəl deyirik.',
      'home.process.4.title': 'Təmir və təhvil',
      'home.process.4.text': 'İşi görür, dəyişən hissələri göstərib maşını təhvil veririk.',
      'home.hours.title': 'Qəbul saatları',
      'home.hours.note': 'Daha az gözləmək üçün gəlməzdən əvvəl zəng edin.',
      'home.cta.title': 'Maşının səsi narahat edirsə, bu gün gətirin',
      'home.cta.text': 'Zəng edin, ən yaxın boş vaxtı deyək.',
      'home.cta.button': 'Əlaqə məlumatları',
      'services.page.title': 'İş növləri',
      'services.page.lead': 'Hər işin qiyməti diaqnostikadan sonra, işə başlamazdan əvvəl deyilir.',
      'about.title': 'Haqqımızda',
      'about.lead': 'Mator Servis mühərrikdən elektrikə qədər hər şeyi bir yerdə görən avtoservisdir.',
      'about.body1': 'Hər maşın əvvəlcə diaqnostikadan keçir, yalnız sonra təmir qərarı verilir. Lazımsız hissə dəyişdirmirik.',
      'about.body2': 'Dəyişdirilən hissələri sizə göstərir, görülən işləri yazılı siyahı ilə təqdim edirik.',
      'about.values.title': 'Servis qaydası',
      'about.value.1.title': 'Əvvəl diaqnostika',
      'about.value.1.text': 'Təxminlə yox, ölçmə ilə qərar veririk.',
      'about.value.2.title': 'Açıq siyahı',
      'about.value.2.text': 'Görülən işlər və hissələr yazılı verilir.',
      'about.value.3.title': 'Köhnə hissə sizindir',
      'about.value.3.text': 'İstəsəniz, dəyişən hissələri geri götürə bilərsiniz.',
      'contact.title': 'Əlaqə',
      'contact.lead': 'Qəbul üçün zəng edin və ya WhatsApp-da yazın.',
      'contact.board.title': 'Qəbul saatları',
      'contact.board.note': 'Bayram günlərində iş saatı əvvəlcədən elan olunur.',
      'contact.phone': '+994 12 000 00 00',
      'contact.whatsapp': '+994 50 000 00 00',
      'contact.email': 'salam@matorservis.az',
      'contact.address': 'Bakı şəhəri',
      'contact.hours': 'B.e. – Şənbə 09:00 – 19:00',
    },
    images: [
      ['home.hero.panel', 'Əyləc diski, diaqnostika cihazı və açar tünd fonda'],
      ['home.hero.float', 'Diaqnostika cihazının göstəricisi'],
      ['home.cta.bg', 'Əyləc diski və mexaniki açar'],
      ['about.main', 'Servis ustası mühərriklə işləyir'],
    ],
    services: [
      ['Kompüter diaqnostikası', 'Xəta kodlarının oxunması və nəticənin başa düşülən izahı.', 'Diaqnostika cihazı'],
      ['Mühərrik təmiri', 'Səs, yağ sızması və gücdə azalma problemlərinin aradan qaldırılması.', 'Mühərrik hissələri'],
      ['Əyləc sistemi', 'Kolodka, disk və əyləc mayesinin yoxlanması və dəyişdirilməsi.', 'Əyləc diski'],
      ['Asqı və sükan', 'Yolun döyülməsi və sükanın yana çəkməsi ilə bağlı təmir.', 'Asqı detalları'],
      ['Yağ və filtr dəyişimi', 'Planlı texniki xidmət: yağ, filtrlər və maye səviyyələri.', 'Yağ dəyişimi'],
      ['Elektrik və akkumulyator', 'İşə düşmə problemləri, akkumulyator və generator yoxlaması.', 'Akkumulyator'],
    ],
  })
}
