import { build } from './build'
import type { SiteConfig } from '../types'

export function createEmlakSite(): SiteConfig {
  return build('emlak', {
    accent: '#b8893b',
    text: {
      'brand.name': 'Dəyər Əmlak',
      'home.hero.title': 'Doğru mənzili tapmaq üçün yanınızdayıq',
      'home.hero.lead':
        'Alış, kirayə və qiymətləndirmə üzrə konkret məsləhət. Baxışları təşkil edir, sənədlərə birgə baxır, danışıqlarda yanınızda oluruq.',
      'home.hero.cta': 'Baxışa yazıl',
      'home.hero.chip': 'Əmlak agentliyi',
      'home.search.title': 'Nə üçün müraciət edirsiniz?',
      'home.search.1.title': 'Alış',
      'home.search.1.text': 'Mənzil, həyət evi, torpaq',
      'home.search.2.title': 'Kirayə',
      'home.search.2.text': 'Uyğun mənzil və müqavilə',
      'home.search.3.title': 'Qiymətləndirmə',
      'home.search.3.text': 'Yazılı qiymət rəyi',
      'home.services.title': 'Nə ilə məşğul oluruq',
      'home.services.link': 'Bütün xidmətlər',
      'home.facts.1.value': '3',
      'home.facts.1.label': 'istiqamət: alış, kirayə və qiymətləndirmə',
      'home.facts.2.value': '1',
      'home.facts.2.label': 'məsul agent sorğudan təhvilə qədər',
      'home.facts.3.value': 'Yazılı',
      'home.facts.3.label': 'razılaşma və qiymət rəyi',
      'home.process.title': 'Əməkdaşlıq necə gedir',
      'home.process.1.title': 'Tələblərin dəqiqləşməsi',
      'home.process.1.text': 'Büdcəni, rayonu və otaq sayını birlikdə müəyyənləşdiririk.',
      'home.process.2.title': 'Baxışlar',
      'home.process.2.text': 'Uyğun variantlara baxış təşkil edir, hər birinin üstünlük və çatışmazlığını deyirik.',
      'home.process.3.title': 'Hüquqi yoxlama',
      'home.process.3.text': 'Seçilən əmlakın sənədlərini razılaşmadan əvvəl yoxlayırıq.',
      'home.process.4.title': 'Sövdələşmə',
      'home.process.4.text': 'Şərtləri yazılı razılaşdırır, təhvil-təslimdə yanınızda oluruq.',
      'home.cta.title': 'Axtardığınız mənzili birlikdə tapaq',
      'home.cta.text': 'Zəng edin, tələblərinizi dinləyib uyğun baxış vaxtı təyin edək.',
      'home.cta.button': 'Əlaqə məlumatları',
      'services.page.title': 'Xidmətlər',
      'services.page.lead': 'Hər əməliyyatın şərtləri razılaşmadan əvvəl yazılı təqdim olunur.',
      'about.title': 'Haqqımızda',
      'about.lead': 'Dəyər Əmlak alıcı, satıcı və kirayəçi arasında aydın ünsiyyət quran agentlikdir.',
      'about.agent.title': 'Məsul agent',
      'about.agent.text': 'Sorğudan açarların təhvilinə qədər sizinlə eyni mütəxəssis işləyir.',
      'about.body1': 'Nə mümkündür, nə vaxt və hansı şərtlərlə: bunları əvvəldən sadə dillə deyirik, vədlə yox, məlumatla işləyirik.',
      'about.body2': 'Əmlakın üstünlüklərini də, çatışmazlıqlarını da açıq izah edirik ki, qərarı tam məlumatla verəsiniz.',
      'about.values.title': 'İş qaydalarımız',
      'about.value.1.title': 'Açıq məlumat',
      'about.value.1.text': 'Əmlakın vəziyyəti və sənədləri barədə bildiyimizi olduğu kimi deyirik.',
      'about.value.2.title': 'Yazılı razılaşma',
      'about.value.2.text': 'Xidmət şərtləri və komissiya işə başlamazdan əvvəl sənədləşir.',
      'about.value.3.title': 'Məxfilik',
      'about.value.3.text': 'Əlaqə məlumatlarınız və tələbləriniz üçüncü şəxslərə ötürülmür.',
      'contact.title': 'Əlaqə',
      'contact.lead': 'Baxış üçün zəng edin və ya WhatsApp-da yazın.',
      'contact.panel.title': 'Birbaşa zəng',
      'contact.phone': '+994 12 000 00 00',
      'contact.whatsapp': '+994 50 000 00 00',
      'contact.email': 'salam@dayeremlak.az',
      'contact.address': 'Bakı şəhəri',
      'contact.hours': 'B.e. – Şənbə 10:00 – 19:00',
    },
    images: [
      ['home.hero.panel', 'Yaşıl fasadlı müasir yaşayış binası, ağaclar və ön planda mənzil açarı'],
      ['home.hero.float', 'Mis rəngli açar və qiymət etiketi'],
      ['home.cta.bg', 'Yaşayış binaları və kiçik həyət evi'],
      ['about.main', 'Agentliyin əməkdaşı yaşayış binasının qarşısında'],
    ],
    services: [
      ['Mənzil alışı', 'Seçimdən sənədləşməyə qədər: baxışlar, hüquqi yoxlama və danışıqlar.', 'Yaşayış binasının fasadı'],
      ['Kirayə', 'Uyğun mənzilin seçilməsi, müqavilənin hazırlanması və təhvil aktı.', 'Kirayə mənzilin açarı'],
      ['Satış', 'Əmlakın hazırlanması, elanın yerləşdirilməsi və alıcılarla görüşlər.', 'Satışa çıxarılan həyət evi'],
      ['Qiymətləndirmə', 'Bazar müqayisəsinə əsaslanan yazılı qiymət rəyi.', 'Qiymət etiketi'],
      ['Hüquqi yoxlama', 'Sənədlərin, yükün və mülkiyyət tarixçəsinin əvvəlcədən yoxlanması.', 'Əmlak sənədləri'],
    ],
  })
}
