import { build } from './build'
import type { SiteConfig } from '../types'

export function createGulSite(): SiteConfig {
  return build('gul', {
    accent: '#b8325f',
    text: {
      'brand.name': 'Qönçə',
      'home.hero.title': 'Hisslər çiçəklə daha asan deyilir',
      'home.hero.lead': 'Mövsümün çiçəklərindən buketlər, qutu kompozisiyaları və kiçik hədiyyələr. Sifarişi verin, Bakı daxilində çatdırırıq.',
      'home.hero.cta': 'Buket sifariş et',
      'home.hero.chip': 'Bakı daxili çatdırılma',
      'home.services.title': 'Kataloqdan',
      'home.services.link': 'Bütün kataloq',
      'home.process.title': 'Sifariş necə hazırlanır',
      'home.process.1.title': 'Seçim',
      'home.process.1.text': 'Kataloqdan seçirsiniz və ya münasibəti və büdcəni yazırsınız.',
      'home.process.2.title': 'Razılaşma',
      'home.process.2.text': 'Florist ilə rəngi, ölçünü və çatdırılma vaxtını dəqiqləşdiririk.',
      'home.process.3.title': 'Hazırlıq',
      'home.process.3.text': 'Buket sifariş günü təzə çiçəklərdən əl ilə yığılır.',
      'home.process.4.title': 'Çatdırılma',
      'home.process.4.text': 'Kuryer ünvana razılaşdırılan vaxtda gətirir.',
      'home.cta.title': 'Kiməsə çiçək göndərmək vaxtıdır',
      'home.cta.text': 'Münasibəti və büdcəni yazın, florist sizə variantlar göndərsin.',
      'home.cta.button': 'Sifariş üçün yazın',
      'services.page.title': 'Kataloq',
      'services.page.lead': 'Çiçək və hədiyyə seçimləri. Hər buket sifariş üzrə yığılır, ona görə rəngi və ölçünü dəyişə bilərik.',
      'about.title': 'Haqqımızda',
      'about.lead': 'Qönçə kiçik çiçək studiyası və hədiyyə mağazasıdır.',
      'about.body1': 'Buketləri hazır şablonla yox, münasibətə, alıcıya və mövsümə baxıb yığırıq. Çiçək bir-birinin yanında düzgün dayananda gözəl görünür.',
      'about.body2': 'Mağazada çiçəklə yanaşı onunla gedən kiçik hədiyyələr də var: şam, açıqca, vaza. Beləliklə hər şey bir yerdə hazır olur.',
      'about.values.title': 'Qaydalarımız',
      'about.value.1.title': 'Mövsümə uyğun',
      'about.value.1.text': 'O vaxt ən yaxşı olan çiçəkləri təklif edirik, mövsümü olmayanı zorla satmırıq.',
      'about.value.2.title': 'Əl işi',
      'about.value.2.text': 'Hər buket ayrıca yığılır, ikisi tam eyni olmur.',
      'about.value.3.title': 'Vaxtında',
      'about.value.3.text': 'Çiçək gecikəndə mənasını itirir, ona görə vaxta ciddi yanaşırıq.',
      'contact.title': 'Əlaqə',
      'contact.lead': 'Sifariş üçün zəng edin və ya WhatsApp-da yazın.',
      'contact.phone': '+994 12 000 00 00',
      'contact.whatsapp': '+994 50 000 00 00',
      'contact.email': 'salam@qoncha.az',
      'contact.address': 'Bakı şəhəri',
      'contact.hours': 'Hər gün 09:00 – 20:00',
    },
    images: [
      ['home.hero.panel', 'Çiçək buketi'],
      ['home.hero.float', 'Lentlə bağlanmış çiçək dəstəsi'],
      ['home.cta.bg', 'Pəncərə qarşısında çiçək kompozisiyası'],
      ['about.main', 'Florist buket yığır'],
    ],
    services: [
      ['Buketlər', 'Mövsümi çiçəklərdən əl ilə yığılmış buketlər, istənilən ölçüdə.', 'Çəhrayı buket'],
      ['Qutu kompozisiyaları', 'Qutuda yığılmış çiçək və yaşıllıq, masaya və hədiyyəyə uyğun.', 'Çiçək qutusu'],
      ['Gəlin buketi', 'Geyimin və mərasimin üslubuna uyğun fərdi buket.', 'Ağ gəlin buketi'],
      ['Tədbir bəzəyi', 'Toy, ad günü və açılış üçün masa və giriş bəzəkləri.', 'Süfrə üstündə çiçək bəzəyi'],
      ['Hədiyyə dəstləri', 'Çiçəyə əlavə olaraq şam, şirniyyat və açıqca ilə hazır dəst.', 'Hədiyyə dəsti'],
      ['Abunə', 'Həftəlik və ya aylıq müntəzəm çiçək çatdırılması.', 'Vazada həftəlik çiçək'],
    ],
  })
}
