import { build } from './build'
import type { SiteConfig } from '../types'

export function createInteryerSite(): SiteConfig {
  return build('interyer', {
    accent: '#8a6f4d',
    text: {
      'brand.name': 'Ölçü Studio',
      'home.hero.title': 'Sakit, dəqiq, sizə uyğun interyer',
      'home.hero.lead': 'Mənzil, ofis və mağaza interyerlərini layihələndirir, mebeli ölçüyə görə sifarişlə hazırlayırıq.',
      'home.hero.cta': 'Görüş təyin et',
      'home.hero.chip': 'Ölçüdən təhvilə qədər',
      'home.services.title': 'Xidmətlərimiz',
      'home.services.link': 'Hamısı',
      'home.process.title': 'İş qaydası',
      'home.process.1.title': 'Görüş',
      'home.process.1.text': 'İstəkləri, büdcəni və məkanı birlikdə müzakirə edirik.',
      'home.process.2.title': 'Ölçmə',
      'home.process.2.text': 'Obyektə gəlib dəqiq ölçü götürür və plan çəkirik.',
      'home.process.3.title': 'Layihə',
      'home.process.3.text': 'Plan, vizual və material siyahısı təsdiq üçün təqdim olunur.',
      'home.process.4.title': 'Təhvil',
      'home.process.4.text': 'Mebel və dekor quraşdırılır, məkan təhvil verilir.',
      'home.cta.title': 'Məkanınız üçün ilk görüş',
      'home.cta.text': 'Ünvanı və istəklərinizi yazın, görüş vaxtını razılaşdıraq.',
      'home.cta.button': 'Əlaqə məlumatları',
      'services.page.title': 'Xidmətlər',
      'services.page.lead': 'İlk görüşdə ehtiyacı dəqiqləşdirir, sonra uyğun xidmət dəstini təklif edirik.',
      'about.title': 'Studiya haqqında',
      'about.lead': 'Ölçü Studio kiçik komandalı interyer dizayn və mebel studiyasıdır.',
      'about.body1': 'Yaxşı interyer ölçüdən başlayır. Ona görə hər layihəyə məkanı santimetrinə qədər öyrənməklə başlayırıq.',
      'about.body2': 'Dizayn və mebel eyni komandada hazırlanır, layihədə çəkilən hər xətt real ölçüyə uyğun gəlir.',
      'about.values.title': 'Prinsiplər',
      'about.value.1.title': 'Dəqiqlik',
      'about.value.1.text': 'Hər ölçü yoxlanılır, hər detal cizgidə göstərilir.',
      'about.value.2.title': 'Sadəlik',
      'about.value.2.text': 'Artıq element əlavə etmirik, məkan nəfəs almalıdır.',
      'about.value.3.title': 'Davamlılıq',
      'about.value.3.text': 'Uzun illər dayanan material və furnitura seçirik.',
      'contact.title': 'Əlaqə',
      'contact.lead': 'Layihənin ünvanını və qısa təsvirini yazın, görüş təyin edək.',
      'contact.phone': '+994 12 000 00 00',
      'contact.whatsapp': '+994 50 000 00 00',
      'contact.email': 'salam@olcu.az',
      'contact.address': 'Bakı şəhəri',
      'contact.hours': 'B.e. – Cümə 10:00 – 18:00',
    },
    images: [
      ['home.hero.panel', 'Qonaq otağında kreslo və döşəmə lampası'],
      ['home.hero.float', 'Bitki və mebel detalı'],
      ['home.cta.bg', 'İşıqlı və sakit otaq'],
      ['about.main', 'Studiya layihə üzərində işləyir'],
    ],
    services: [
      ['Dizayn layihəsi', 'Planlaşdırma, 3D vizuallar və material siyahısı ilə tam interyer layihəsi.', 'Otaq planı və vizual'],
      ['Ölçmə və plan', 'Məkanın dəqiq ölçülməsi və mebel yerləşdirmə planı.', 'Ölçü cizgisi'],
      ['Mebel sifarişi', 'Mətbəx, qarderob və built-in mebel ölçüyə görə hazırlanır.', 'Sifarişlə hazırlanan mebel'],
      ['Komplektləşdirmə', 'İşıqlandırma, parça və dekor elementlərinin seçimi və alınması.', 'Material nümunələri'],
      ['Avtor nəzarəti', 'İcra zamanı layihənin düzgün həyata keçirilməsinə nəzarət edirik.', 'Obyektdə yoxlama'],
    ],
  })
}
