import { img, service } from '../default-site'
import type { SiteConfig, TemplateId } from '../types'

interface Spec {
  accent: string
  text: Record<string, string>
  images: [string, string, string?, number?, number?][]
  services: [string, string, string, string?][]
}

function build(template: TemplateId, spec: Spec): SiteConfig {
  return {
    version: 1,
    template,
    theme: { accent: spec.accent },
    logo: img('Loqo'),
    text: { 'footer.text': 'Bütün hüquqlar qorunur.', ...spec.text },
    images: Object.fromEntries(spec.images.map(([key, alt, src, fx, fy]) => [key, img(alt, fx, fy, src)])),
    services: spec.services.map(([title, text, alt, src], i) => service(`s${i + 1}`, title, text, alt, src)),
    extras: { home: [], services: [], about: [], contact: [] },
    hidden: {},
  }
}

export function createHuquqSite(): SiteConfig {
  return build('huquq', {
    accent: '#9a6b1f',
    text: {
      'brand.name': 'Hüquq Evi',
      'home.hero.title': 'Hüquqi məsələnizi sakit və dəqiq həll edirik',
      'home.hero.lead': 'Mülki, ailə və əmək mübahisələri üzrə vəkil məsləhəti. İlk görüşdə vəziyyətinizi dinləyir, mümkün yolları izah edirik.',
      'home.hero.cta': 'Məsləhətə yazıl',
      'home.hero.chip': 'Vəkil bürosu',
      'home.services.title': 'Fəaliyyət sahələri',
      'home.services.link': 'Hamısı',
      'home.process.title': 'Necə işləyirik',
      'home.process.1.title': 'İlkin görüş',
      'home.process.1.text': 'Vəziyyətinizi dinləyir, sənədlərə baxırıq.',
      'home.process.2.title': 'Hüquqi qiymətləndirmə',
      'home.process.2.text': 'Mümkün yolları və riskləri açıq izah edirik.',
      'home.process.3.title': 'Yazılı razılaşma',
      'home.process.3.text': 'İşin həcmi və ödəniş qabaqcadan razılaşdırılır.',
      'home.process.4.title': 'İcra',
      'home.process.4.text': 'Sənədləri hazırlayır, sizi danışıqlarda və məhkəmədə təmsil edirik.',
      'home.cta.title': 'Sənədləriniz əlinizdədirsə, görüşə gətirin',
      'home.cta.text': 'Zəng edin, sizə uyğun vaxt təyin edək.',
      'home.cta.button': 'Əlaqə məlumatları',
      'services.page.title': 'Fəaliyyət sahələri',
      'services.page.lead': 'Hər işin şərtləri ilkin görüşdə yazılı razılaşdırılır.',
      'about.title': 'Haqqımızda',
      'about.lead': 'Hüquq Evi kiçik vəkil bürosudur.',
      'about.body1': 'Hər işə fərdi yanaşırıq: nə edə biləcəyimizi və nəyin mümkün olmadığını əvvəldən açıq deyirik.',
      'about.body2': 'Müştəri məlumatları məxfi saxlanılır, işin gedişi barədə müntəzəm məlumat verilir.',
      'about.values.title': 'Prinsiplərimiz',
      'about.value.1.title': 'Məxfilik',
      'about.value.1.text': 'Müraciətiniz və sənədləriniz üçüncü şəxslərə verilmir.',
      'about.value.2.title': 'Açıq qiymətləndirmə',
      'about.value.2.text': 'Şansları olduğu kimi izah edirik.',
      'about.value.3.title': 'Yazılı razılaşma',
      'about.value.3.text': 'Şərtlər işə başlamazdan əvvəl sənədləşir.',
      'contact.title': 'Əlaqə',
      'contact.lead': 'Görüş üçün zəng edin və ya WhatsApp-da yazın.',
      'contact.phone': '+994 12 000 00 00',
      'contact.whatsapp': '+994 50 000 00 00',
      'contact.email': 'salam@huquqevi.az',
      'contact.address': 'Bakı şəhəri',
      'contact.hours': 'B.e. – Cümə 10:00 – 18:00',
    },
    images: [
      ['home.hero.panel', 'Ədalət tərəzisi, hakim çəkici və qanun kitabları', '/images/huquq/hero.webp'],
      ['home.cta.bg', 'Kitablar üzərində hakim çəkici və ədalət tərəzisi', '/images/huquq/cokic-kitab.webp'],
      ['about.main', 'Vəkil iş masasında sənədlə işləyir', '/images/huquq/about.webp', 42, 50],
    ],
    services: [
      ['Mülki mübahisələr', 'Borc, mülkiyyət və müqavilə mübahisələrində müraciət və məhkəmə təmsilçiliyi.', 'Hakim çəkici və qanun kitabları', '/images/huquq/mulki.webp'],
      ['Ailə hüququ', 'Boşanma, nəfəqə və uşağın yaşayış yeri məsələləri.', 'Kitablar üzərində hakim çəkici və ədalət tərəzisi', '/images/huquq/cokic-kitab.webp'],
      ['Əmək münasibətləri', 'İşdən çıxarılma, əmək müqaviləsi və kompensasiya mübahisələri.', 'Hakim çəkici', '/images/huquq/emek.webp'],
      ['Müqavilələr və sənədlər', 'Müqavilənin hazırlanması, yoxlanması və hüquqi rəyi.', 'Açıq qanun kitabı və ədalət tərəzisi', '/images/huquq/muqavile.webp'],
    ],
  })
}

export function createGozellikSite(): SiteConfig {
  return build('gozellik', {
    accent: '#b03a63',
    text: {
      'brand.name': 'Lalə Gözəllik',
      'home.hero.title': 'Özünüzü yaxşı hiss edəcəyiniz bir məkan',
      'home.hero.lead': 'Saç, dırnaq və üz baxımı bir yerdə. Qəbul əvvəlcədən vaxtla olur, gözləmədən.',
      'home.hero.cta': 'Vaxt götür',
      'home.hero.chip': 'Əvvəlcədən yazılın',
      'home.services.title': 'Xidmətlərimiz',
      'home.services.link': 'Hamısı',
      'home.process.title': 'Qəbul necə keçir',
      'home.process.1.title': 'Yazılın',
      'home.process.1.text': 'Zəng və ya WhatsApp ilə sizə uyğun vaxtı seçirik.',
      'home.process.2.title': 'Məsləhət',
      'home.process.2.text': 'Ustanın sizinlə nəticəni əvvəlcədən müzakirə edir.',
      'home.process.3.title': 'Prosedur',
      'home.process.3.text': 'İşlər təmiz alətlərlə, sakit mühitdə görülür.',
      'home.process.4.title': 'Baxım təlimatı',
      'home.process.4.text': 'Evdə necə saxlamağı izah edirik.',
      'home.cta.title': 'Növbəti görüşünüz üçün vaxt seçin',
      'home.cta.text': 'Zəng edin, ən yaxın boş vaxtı deyək.',
      'home.cta.button': 'Əlaqə məlumatları',
      'services.page.title': 'Xidmətlər',
      'services.page.lead': 'Hər xidmətin qiyməti vaxt götürəndə bildirilir.',
      'about.title': 'Haqqımızda',
      'about.lead': 'Lalə Gözəllik kiçik salondur, hər müştəriyə vaxt ayırırıq.',
      'about.body1': 'Salonda hər usta öz sahəsi üzrə işləyir və prosedurdan əvvəl istəyinizi dinləyir.',
      'about.body2': 'Alətlər hər müştəridən sonra təmizlənir, vaxt isə əvvəlcədən ayrılır.',
      'about.values.title': 'Prinsiplərimiz',
      'about.value.1.title': 'Gigiyena',
      'about.value.1.text': 'Alətlər hər müştəridən sonra emal olunur.',
      'about.value.2.title': 'Dəqiq vaxt',
      'about.value.2.text': 'Yazılan vaxta görə qəbul edirik.',
      'about.value.3.title': 'Açıq məsləhət',
      'about.value.3.text': 'Nəticə və qiymət prosedurdan əvvəl deyilir.',
      'contact.title': 'Əlaqə',
      'contact.lead': 'Vaxt götürmək üçün zəng edin və ya WhatsApp-da yazın.',
      'contact.phone': '+994 12 000 00 00',
      'contact.whatsapp': '+994 50 000 00 00',
      'contact.email': 'salam@lalegozellik.az',
      'contact.address': 'Bakı şəhəri',
      'contact.hours': 'Hər gün 10:00 – 20:00',
    },
    images: [
      ['home.hero.panel', 'Saç ustası müştəri ilə'],
      ['home.hero.float', 'Üz baxımı prosedurası'],
      ['home.hero.third', 'Manikür aksesuarları'],
      ['home.cta.bg', 'Salonun interyeri'],
      ['about.main', 'Salonun ustaları'],
    ],
    services: [
      ['Saç kəsimi və boyama', 'Kəsim, boyama, qırışdırma və baxım prosedurları.', 'Saç ustası işləyir'],
      ['Manikür və pedikür', 'Klassik və gel-lak örtüklü manikür, pedikür.', 'Manikür prosesi'],
      ['Üz baxımı', 'Təmizləmə, nəmləndirmə və yüngül masaj.', 'Üz baxımı'],
      ['Makiyaj', 'Gündəlik və tədbir makiyajı.', 'Makiyaj ustası'],
    ],
  })
}

export function createIdmanSite(): SiteConfig {
  return build('idman', {
    accent: '#d6ff3c',
    text: {
      'brand.name': 'Güc Zal',
      'home.hero.title': 'Formanı bu gün qur',
      'home.hero.lead': 'Təlimçi nəzarəti ilə məşq, qrup dərsləri və fərdi proqram.',
      'home.hero.cta': 'Sınaq məşqinə yazıl',
      'home.hero.chip': 'HƏRƏKƏT',
      'home.services.title': 'Məşq növləri',
      'home.services.link': 'Hamısı',
      'home.process.title': 'Necə başlayırsan',
      'home.process.1.title': 'Tanışlıq',
      'home.process.1.text': 'Məqsədini və sağlamlıq vəziyyətini danışırıq.',
      'home.process.2.title': 'Qiymətləndirmə',
      'home.process.2.text': 'Başlanğıc nəticələrini ölçürük.',
      'home.process.3.title': 'Proqram',
      'home.process.3.text': 'Sənə uyğun həftəlik məşq planı qurulur.',
      'home.process.4.title': 'İzləmə',
      'home.process.4.text': 'Nəticələr müntəzəm yoxlanılır.',
      'home.cta.title': 'İlk addımı indi at',
      'home.cta.text': 'Zəng et, sınaq məşqi üçün vaxt seçək.',
      'home.cta.button': 'Əlaqə məlumatları',
      'services.page.title': 'Məşq növləri',
      'services.page.lead': 'Hər proqram təlimçi ilə razılaşdırılır.',
      'about.title': 'Haqqımızda',
      'about.lead': 'Güc Zal təlimçi nəzarəti ilə işləyən idman zalıdır.',
      'about.body1': 'Hər üzv məşqə başlamazdan əvvəl təlimçi ilə məqsədini və imkanlarını müzakirə edir.',
      'about.body2': 'Qrup və fərdi məşqlər cədvəl üzrə keçirilir, avadanlıq müntəzəm yoxlanılır.',
      'about.values.title': 'Prinsiplərimiz',
      'about.value.1.title': 'Təhlükəsizlik',
      'about.value.1.text': 'Texnika əvvəlcə öyrədilir, yük sonra artırılır.',
      'about.value.2.title': 'Fərdi plan',
      'about.value.2.text': 'Proqram hər kəs üçün ayrıca qurulur.',
      'about.value.3.title': 'Müntəzəmlik',
      'about.value.3.text': 'Cədvəl və nəticələr izlənilir.',
      'contact.title': 'Əlaqə',
      'contact.lead': 'Sınaq məşqi üçün zəng et və ya WhatsApp-da yaz.',
      'contact.phone': '+994 12 000 00 00',
      'contact.whatsapp': '+994 50 000 00 00',
      'contact.email': 'salam@guczal.az',
      'contact.address': 'Bakı şəhəri',
      'contact.hours': 'Hər gün 07:00 – 23:00',
    },
    images: [
      ['home.hero.panel', 'Məşq edən idmançı'],
      ['home.hero.float', 'İdman avadanlığı'],
      ['home.cta.bg', 'İdman zalı'],
      ['about.main', 'Təlimçi komandası'],
    ],
    services: [
      ['Fərdi məşq', 'Təlimçi ilə birə-bir proqram və texnika nəzarəti.', 'Təlimçi ilə məşq'],
      ['Qrup dərsləri', 'Cədvəl üzrə kiçik qruplarla məşqlər.', 'Qrup məşqi'],
      ['Funksional təlim', 'Güc, dözümlülük və hərəkətlilik üzrə kompleks məşq.', 'Funksional məşq'],
      ['Qidalanma məsləhəti', 'Məqsədinə uyğun qidalanma üzrə ümumi tövsiyələr.', 'Qidalanma məsləhəti'],
    ],
  })
}

export function createTikintiSite(): SiteConfig {
  return build('tikinti', {
    accent: '#c25a00',
    text: {
      'brand.name': 'Təməl Tikinti',
      'home.hero.title': 'Təmir və tikinti işləri müqavilə və cədvəllə',
      'home.hero.lead': 'Mənzil və ofis təmiri, cari tikinti işləri. Smeta işə başlamazdan əvvəl təqdim olunur.',
      'home.hero.cta': 'Smeta istə',
      'home.hero.chip': 'Obyektə baxış',
      'home.services.title': 'İş növləri',
      'home.services.link': 'Hamısı',
      'home.process.title': 'İş mərhələləri',
      'home.process.1.title': 'Obyektə baxış',
      'home.process.1.text': 'Ustamız yerində ölçü götürür, istəklərinizi dinləyir.',
      'home.process.2.title': 'Smeta və müqavilə',
      'home.process.2.text': 'Material, iş və müddət yazılı razılaşdırılır.',
      'home.process.3.title': 'İcra',
      'home.process.3.text': 'İşlər cədvəl üzrə görülür, gedişat barədə məlumat verilir.',
      'home.process.4.title': 'Təhvil',
      'home.process.4.text': 'Birgə yoxlama aparılır və obyekt təhvil verilir.',
      'home.cta.title': 'Obyektinizə baxış üçün vaxt seçin',
      'home.cta.text': 'Zəng edin, ustanı ünvana göndərək.',
      'home.cta.button': 'Əlaqə məlumatları',
      'services.page.title': 'İş növləri',
      'services.page.lead': 'Qiymət obyektə baxışdan sonra smetada göstərilir.',
      'about.title': 'Haqqımızda',
      'about.lead': 'Təməl Tikinti təmir və tikinti işləri görən komandadır.',
      'about.body1': 'İşə başlamazdan əvvəl smeta və cədvəl yazılı təqdim edilir, dəyişikliklər sizinlə razılaşdırılır.',
      'about.body2': 'Obyekt təhvil verilməzdən əvvəl birlikdə yoxlanılır.',
      'about.values.title': 'Prinsiplərimiz',
      'about.value.1.title': 'Yazılı smeta',
      'about.value.1.text': 'İş və material xərcləri əvvəlcədən göstərilir.',
      'about.value.2.title': 'Cədvələ əməl',
      'about.value.2.text': 'Mərhələlər razılaşdırılmış vaxtda tamamlanır.',
      'about.value.3.title': 'Birgə təhvil',
      'about.value.3.text': 'Nəticəni sizinlə yoxlayırıq.',
      'contact.title': 'Əlaqə',
      'contact.lead': 'Obyektə baxış üçün zəng edin və ya WhatsApp-da yazın.',
      'contact.phone': '+994 12 000 00 00',
      'contact.whatsapp': '+994 50 000 00 00',
      'contact.email': 'salam@temeltikinti.az',
      'contact.address': 'Bakı şəhəri',
      'contact.hours': 'B.e. – Şənbə 09:00 – 18:00',
    },
    images: [
      ['home.hero.panel', 'Tikinti obyektində iş'],
      ['home.hero.float', 'Layihə planı'],
      ['home.cta.bg', 'Təmir olunmuş otaq'],
      ['about.main', 'Təmir komandası'],
    ],
    services: [
      ['Mənzil təmiri', 'Kosmetik və əsaslı təmir, divar, döşəmə və tavan işləri.', 'Mənzildə təmir işi'],
      ['Ofis və kommersiya', 'Ofis, mağaza və kafe üçün təmir və yenidən planlaşdırma.', 'Ofis təmiri'],
      ['Dizayn və layihə', 'Plan, material seçimi və 3D vizual.', 'Layihə planı'],
      ['Mühəndis sistemləri', 'Elektrik, santexnika və ventilyasiya işləri.', 'Elektrik quraşdırılması'],
    ],
  })
}

export function createKursSite(): SiteConfig {
  return build('kurs', {
    accent: '#d4380d',
    text: {
      'brand.name': 'Bilik Mərkəzi',
      'home.hero.title': 'Öyrənmək üçün düzgün başlanğıc',
      'home.hero.lead': 'İngilis dili, riyaziyyat və kompüter kursları kiçik qruplarla.',
      'home.hero.cta': 'Qeydiyyatdan keç',
      'home.hero.chip': 'Yeni qrup açılır',
      'home.services.title': 'Kurslarımız',
      'home.services.link': 'Hamısı',
      'home.process.title': 'Necə qoşulursan',
      'home.process.1.title': 'Qeydiyyat',
      'home.process.1.text': 'Zəng və ya WhatsApp ilə müraciət edirsən.',
      'home.process.2.title': 'Səviyyə yoxlanışı',
      'home.process.2.text': 'Qısa söhbət və test ilə səviyyəni müəyyən edirik.',
      'home.process.3.title': 'Qrup seçimi',
      'home.process.3.text': 'Sənə uyğun qrup və vaxt təklif olunur.',
      'home.process.4.title': 'Dərslər',
      'home.process.4.text': 'Dərslər cədvəl üzrə başlayır.',
      'home.cta.title': 'Boş yer qalıbmı? Soruş',
      'home.cta.text': 'Zəng et, qrupların boş yerlərini deyək.',
      'home.cta.button': 'Əlaqə məlumatları',
      'services.page.title': 'Kurslar',
      'services.page.lead': 'Qrupların cədvəli və qiyməti qeydiyyatda bildirilir.',
      'about.title': 'Haqqımızda',
      'about.lead': 'Bilik Mərkəzi kiçik qruplarla işləyən təhsil mərkəzidir.',
      'about.body1': 'Hər qrupda şagird sayı məhduddur ki, müəllim hər kəsə vaxt ayıra bilsin.',
      'about.body2': 'Dərslər cədvəl üzrə keçirilir, valideynlərə irəliləyiş barədə məlumat verilir.',
      'about.values.title': 'Prinsiplərimiz',
      'about.value.1.title': 'Kiçik qruplar',
      'about.value.1.text': 'Müəllim hər şagirdlə ayrıca məşğul olur.',
      'about.value.2.title': 'Aydın plan',
      'about.value.2.text': 'Hər kursun proqramı əvvəlcədən göstərilir.',
      'about.value.3.title': 'Valideynlə əlaqə',
      'about.value.3.text': 'İrəliləyiş barədə müntəzəm məlumat verilir.',
      'contact.title': 'Əlaqə',
      'contact.lead': 'Qeydiyyat üçün zəng edin və ya WhatsApp-da yazın.',
      'contact.phone': '+994 12 000 00 00',
      'contact.whatsapp': '+994 50 000 00 00',
      'contact.email': 'salam@bilikmerkezi.az',
      'contact.address': 'Bakı şəhəri',
      'contact.hours': 'B.e. – Şənbə 09:00 – 20:00',
    },
    images: [
      ['home.hero.panel', 'Dərsdə şagirdlər'],
      ['home.hero.float', 'Dərs vəsaitləri'],
      ['home.cta.bg', 'Sinif otağı'],
      ['about.main', 'Müəllim heyəti'],
    ],
    services: [
      ['İngilis dili', 'Başlanğıcdan irəli səviyyəyə qədər qrup dərsləri.', 'İngilis dili dərsi'],
      ['Riyaziyyat', 'Məktəb proqramı və imtahana hazırlıq.', 'Riyaziyyat dərsi'],
      ['Proqramlaşdırma', 'Uşaq və yeniyetmələr üçün başlanğıc kurs.', 'Kompüter dərsi'],
      ['Məktəbə hazırlıq', 'Oxu, yazı və riyaziyyatın əsasları.', 'Kiçik uşaqlarla dərs'],
    ],
  })
}

export function createStudiyaSite(): SiteConfig {
  return build('studiya', {
    accent: '#e4572e',
    text: {
      'brand.name': 'Kadr Studio',
      'home.hero.title': 'Yaddaşa çevrilən kadrlar',
      'home.hero.lead': 'Portret, məhsul və tədbir çəkilişləri. Seçilmiş kadrlar redaktə olunub təqdim edilir.',
      'home.hero.cta': 'Çəkiliş sifariş et',
      'home.hero.chip': 'Foto və video',
      'home.services.title': 'Çəkiliş növləri',
      'home.services.link': 'Hamısı',
      'home.process.title': 'Çəkiliş necə keçir',
      'home.process.1.title': 'Brif',
      'home.process.1.text': 'Məqsədi, məkanı və üslubu müzakirə edirik.',
      'home.process.2.title': 'Çəkiliş',
      'home.process.2.text': 'Studiyada və ya ünvanda çəkiliş aparılır.',
      'home.process.3.title': 'Redaktə',
      'home.process.3.text': 'Seçilmiş kadrlar rəng və retuş ilə işlənir.',
      'home.process.4.title': 'Təhvil',
      'home.process.4.text': 'Hazır fayllar razılaşdırılmış formatda göndərilir.',
      'home.cta.title': 'Çəkiliş üçün tarix seçin',
      'home.cta.text': 'Zəng edin, boş günləri deyək.',
      'home.cta.button': 'Əlaqə məlumatları',
      'services.page.title': 'Çəkiliş növləri',
      'services.page.lead': 'Qiymət çəkilişin növündən və müddətindən asılıdır.',
      'about.title': 'Haqqımızda',
      'about.lead': 'Kadr Studio foto və video çəkilişləri ilə məşğul olur.',
      'about.body1': 'Çəkilişdən əvvəl məqsəd və üslub müzakirə olunur ki, nəticə gözləntinizə uyğun olsun.',
      'about.body2': 'Hazır kadrlar redaktə olunur və razılaşdırılmış müddətdə təhvil verilir.',
      'about.values.title': 'Prinsiplərimiz',
      'about.value.1.title': 'Aydın brif',
      'about.value.1.text': 'Çəkilişdən əvvəl hər şey razılaşdırılır.',
      'about.value.2.title': 'Təbii görüntü',
      'about.value.2.text': 'Həddindən artıq retuşdan çəkinirik.',
      'about.value.3.title': 'Vaxtında təhvil',
      'about.value.3.text': 'Fayllar vəd olunan tarixdə göndərilir.',
      'contact.title': 'Əlaqə',
      'contact.lead': 'Çəkiliş üçün zəng edin və ya WhatsApp-da yazın.',
      'contact.phone': '+994 12 000 00 00',
      'contact.whatsapp': '+994 50 000 00 00',
      'contact.email': 'salam@kadrstudio.az',
      'contact.address': 'Bakı şəhəri',
      'contact.hours': 'Hər gün 10:00 – 20:00',
    },
    images: [
      ['home.hero.panel', 'Fotoqraf iş başında'],
      ['home.hero.float', 'Studiya işıqları'],
      ['home.cta.bg', 'Foto studiyanın içi'],
      ['about.main', 'Studiyanın komandası'],
    ],
    services: [
      ['Portret çəkilişi', 'Fərdi, ailə və korporativ portretlər.', 'Portret çəkilişi'],
      ['Məhsul çəkilişi', 'Mağaza və sosial şəbəkə üçün məhsul fotoları.', 'Məhsul çəkilişi'],
      ['Tədbir çəkilişi', 'Toy, ad günü və korporativ tədbirlərin foto və videosu.', 'Tədbir çəkilişi'],
      ['Video montaj', 'Çəkilmiş materialın montajı və rənglənməsi.', 'Montaj prosesi'],
    ],
  })
}
