import { build } from './build'
import type { SiteConfig } from '../types'

export function createStomatSite(): SiteConfig {
  return build('stomat', {
    accent: '#0f8f86',
    text: {
      'brand.name': 'Ağ Təbəssüm',
      'home.hero.title': 'Dişləriniz üçün sakit və diqqətli qəbul',
      'home.hero.lead':
        'Müayinə, təmizləmə və müalicə bir klinikada. Hər mərhələni əvvəlcədən izah edir, qərarı birlikdə veririk.',
      'home.hero.cta': 'Qəbula yazıl',
      'home.hero.chip': 'Stomatoloji klinika',
      'home.hero.tag1': 'Müayinə',
      'home.hero.tag2': 'Təmizləmə',
      'home.services.title': 'Nələrlə kömək edirik',
      'home.services.link': 'Bütün xidmətlər',
      'home.process.title': 'Qəbul necə keçir',
      'home.process.1.title': 'Tanışlıq',
      'home.process.1.text': 'Şikayətlərinizi dinləyir, suallarınıza cavab veririk.',
      'home.process.2.title': 'Müayinə',
      'home.process.2.text': 'Dişlərə baxır, lazım olsa şəkil çəkdiririk.',
      'home.process.3.title': 'Plan',
      'home.process.3.text': 'Mərhələləri və müddəti sizinlə birlikdə müəyyənləşdiririk.',
      'home.process.4.title': 'Müalicə',
      'home.process.4.text': 'Hər addımı əvvəlcədən izah edərək müalicəyə başlayırıq.',
      'home.cta.title': 'Təbəssümünüz üçün vaxt seçək',
      'home.cta.text': 'Zəng edin, sizə uyğun qəbul vaxtı təyin edək.',
      'home.cta.button': 'Əlaqə məlumatları',
      'services.page.title': 'Xidmətlər',
      'services.page.lead': 'Müalicənin qiyməti və mərhələləri müayinədən sonra yazılı təqdim olunur.',
      'about.title': 'Haqqımızda',
      'about.lead': 'Ağ Təbəssüm rahat və sakit mühitdə qəbul edən stomatoloji klinikadır.',
      'about.body1': 'Qorxu və narahatlıq normaldır. Müalicəyə başlamazdan əvvəl nə ediləcəyini sadə dillə izah edirik.',
      'about.body2': 'Lazım olsa fasilə veririk, suallarınıza vaxt ayırırıq. Sizi tələsdirmirik.',
      'about.values.title': 'Tez-tez verilən suallar',
      'about.value.1.title': 'Qorxuram, nə edim?',
      'about.value.1.text': 'Əvvəlcə söhbət edirik. İstədiyiniz an əlinizi qaldırıb fasilə istəyə bilərsiniz.',
      'about.value.2.title': 'Qiyməti əvvəlcədən deyirsiniz?',
      'about.value.2.text': 'Müayinədən sonra plan və qiymət yazılı təqdim olunur.',
      'about.value.3.title': 'Alətlər necə təmizlənir?',
      'about.value.3.text': 'Alətlər hər qəbuldan sonra sterilizasiya olunur, birdəfəlik materiallar dəyişdirilir.',
      'contact.title': 'Əlaqə',
      'contact.lead': 'Qəbul üçün zəng edin və ya WhatsApp-da yazın.',
      'contact.rules.title': 'Qəbula gələndə',
      'contact.rules.1': 'Əvvəlki müayinə kağızlarınız varsa, götürün.',
      'contact.rules.2': 'Sualınız varsa, əvvəlcədən yazıb gətirə bilərsiniz.',
      'contact.rules.3': 'Vaxtınızı dəyişmək istəsəniz, bir gün əvvəl xəbər verin.',
      'contact.phone': '+994 12 000 00 00',
      'contact.whatsapp': '+994 50 000 00 00',
      'contact.email': 'salam@agtebessum.az',
      'contact.address': 'Bakı şəhəri',
      'contact.hours': 'B.e. – Şənbə 10:00 – 19:00',
    },
    images: [
      ['home.hero.panel', 'Böyük ağ diş və təbəssüm xətti, ətrafda nanə rəngli dairələr'],
      ['home.hero.float', 'Diş fırçası və yumşaq nanə fon'],
      ['home.hero.third', 'Kiçik diş və parıltılar'],
      ['home.cta.bg', 'Gülümsəyən diş illüstrasiyası'],
      ['about.main', 'Diş və təbəssüm təsvir edilən yumşaq illüstrasiya'],
    ],
    services: [
      ['Müayinə və məsləhət', 'Dişlərin vəziyyətinə baxış və müalicə planının izahı.', 'Müayinə'],
      ['Peşəkar təmizlik', 'Diş daşı və ləkələrin təmizlənməsi.', 'Diş təmizliyi'],
      ['Plomb və müalicə', 'Kariesin müalicəsi və dişin bərpası.', 'Diş müalicəsi'],
      ['Kanal müalicəsi', 'Diş kanallarının təmizlənməsi və möhürlənməsi.', 'Kanal müalicəsi'],
      ['Ağartma', 'Dişlərin rənginin yüngül açılması.', 'Diş ağartma'],
      ['Uşaq stomatologiyası', 'Uşaqlar üçün sakit və oyunlu tanışlıq qəbulu.', 'Uşaq qəbulu'],
    ],
  })
}
