import { build } from './build'
import type { SiteConfig } from '../types'

export function createTurizmSite(): SiteConfig {
  return build('turizm', {
    accent: '#e2543b',
    text: {
      'brand.name': 'Yol Əhli',
      'home.hero.title': 'Bu dəfə hara gedirik?',
      'home.hero.lead': 'Aviabilet, otel, viza və transfer bir yerdə. Tarixləri və büdcənizi deyin, sizə uyğun marşrutları göndərək.',
      'home.hero.cta': 'Təklif istə',
      'home.hero.chip': 'Bakıdan yola düşürük',
      'home.services.title': 'Nələri təşkil edirik',
      'home.services.link': 'Hamısı',
      'home.process.title': 'Yola necə çıxırıq',
      'home.process.1.title': 'Sorğu',
      'home.process.1.text': 'Hara, nə vaxt və neçə nəfər getmək istədiyinizi yazırsınız.',
      'home.process.2.title': 'Seçimlər',
      'home.process.2.text': 'Büdcənizə uyğun bir neçə marşrut göndəririk, birini seçirsiniz.',
      'home.process.3.title': 'Rəsmiləşdirmə',
      'home.process.3.text': 'Rezervasiyanı edir, lazım olan sənədləri hazırlayırıq.',
      'home.process.4.title': 'Yola düşmə',
      'home.process.4.text': 'Biletlər və səfər planı yola çıxmazdan əvvəl sizdə olur.',
      'home.cta.title': 'Növbəti səfəri planlayaq',
      'home.cta.text': 'İstiqaməti və tarixləri deyin, uyğun variantları göndərək.',
      'home.cta.button': 'Bizimlə əlaqə',
      'services.page.title': 'Səyahət xidmətləri',
      'services.page.lead': 'Hər səfər üçün istiqaməti, tarixləri və büdcəni birlikdə dəqiqləşdiririk.',
      'about.title': 'Haqqımızda',
      'about.lead': 'Yol Əhli səyahəti stressiz etmək üçün çalışan kiçik turizm agentliyidir.',
      'about.body1': 'Hər səfərə fərdi yanaşırıq: hara getmək istədiyinizi, kiminlə getdiyinizi və vaxtınızı nəyə ayırmaq istədiyinizi soruşub planı ona görə quraq.',
      'about.body2': 'Rezervasiya, sənəd və transfer məsələlərini özümüz izləyirik ki, siz yalnız yola hazırlaşasınız.',
      'about.values.title': 'Səfərə baxışımız',
      'about.value.1.title': 'Aydın qiymət',
      'about.value.1.text': 'Təklifdə nələrin daxil olduğu açıq yazılır, gizli ödəniş olmur.',
      'about.value.2.title': 'Real təsvir',
      'about.value.2.text': 'Otel və marşrutu olduğu kimi təqdim edirik, gözləntini şişirtmirik.',
      'about.value.3.title': 'Yolda yanınızda',
      'about.value.3.text': 'Səfər zamanı sual yaranarsa, zəng və ya mesajla cavab veririk.',
      'contact.title': 'Əlaqə',
      'contact.lead': 'Hara getmək istədiyinizi yazın, sizə uyğun variantları göndərək.',
      'contact.phone': '+994 12 000 00 00',
      'contact.whatsapp': '+994 50 000 00 00',
      'contact.email': 'salam@yolehli.az',
      'contact.address': 'Bakı şəhəri',
      'contact.hours': 'B.e. – Şənbə 10:00 – 19:00',
    },
    images: [
      ['home.hero.panel', 'Dağ yolunda səyahətçilər'],
      ['home.hero.float', 'Dənizkənarı kurort'],
      ['home.hero.third', 'Qədim şəhərin küçəsi'],
      ['home.cta.bg', 'Sahilə doğru uzanan yol'],
      ['about.main', 'Komanda səyahət planı hazırlayır'],
    ],
    services: [
      ['Aviabilet və otel', 'Tarixlərə və büdcəyə görə reys və yaşayış yerlərinin müqayisəsi.', 'Dənizə baxan otel və təyyarə bileti'],
      ['Hazır turlar', 'Uçuş, yaşayış və transferin bir paketdə olduğu qrup və fərdi turlar.', 'Tur paketi üçün marşrut xəritəsi'],
      ['Viza və sənədlər', 'Sənəd siyahısının hazırlanması və müraciətin müşayiəti.', 'Pasport və viza sənədləri'],
      ['Ailə səfərləri', 'Uşaqlarla rahat reys, otel və gündəlik proqram seçimi.', 'Sahildə ailə'],
      ['Yerli gəzintilər', 'Bakıdan Qəbələ, Şəki, Quba və Xınalığa bir və iki günlük gəzintilər.', 'Dağ kəndinə gedən yol'],
      ['Transfer və bələdçi', 'Hava limanından otelə transfer və yerli bələdçi xidməti.', 'Hava limanında qarşılanma'],
    ],
  })
}
